// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://olaulusscvlqivnjmqav.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9sYXVsdXNzY3ZscWl2bmptcWF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTU3NTUsImV4cCI6MjA2NDE5MTc1NX0.LPz89Qo6dLhvhlf-XUEU2qEbHBmn3DJEfxZlSvkwdHk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);